version: 2
updates:
# poetry is part of the pip ecosystem
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "Sphinx"
    # conflicts with sphinx-design and waiting on: https://github.com/executablebooks/sphinx-design/pull/131
    versions: [">=7"]
