version: 2
updates:
# poetry is part of the pip ecosystem
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "Sphinx"
    # conflicts with a dependency of core, tracked in inmanta/infra-tickets#121
    versions: [">=6"]
