version: 2
updates:
# poetry is part of the pip ecosystem
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
   - dependency-name: "asyncpg"
   - dependency-name: "flake8"
     versions: [">=4.0.0"]
     # flake8 >= 4.0 conflicts with importlib_metadata > 4.3 as per this: PyCQA/flake8#1438
  - dependency-name: "sphinx tabs"
    versions: [">=3.3.1"]
      # sphinx tabs >=3.3.1 requires docutils > 0.18 and sphinx rtd theme is not compatible with docutils >= 0.18
- dependency-name: "Sphinx"
    versions: [">=4.5.0"]
      # sphinx-tabs (3.3.1) depends on sphinx (>=2,<5)      